# Render Blueprint for LLM Directory
# IMPORTANT: This deploys as a STATIC SITE, not a web service

services:
  - type: web
    name: llm-directory
    env: static
    buildCommand: npm ci && npm run build
    staticPublishPath: dist
    pullRequestPreviewsEnabled: true
    headers:
      - path: /*
        name: Cache-Control
        value: public, max-age=3600
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

# Note: The /api/notify-visit.js serverless function is Vercel-specific
# and will not work on Render static sites. To use API functions on Render,
# you would need to deploy a separate web service with Express.js backend.
